### ISSUE TITLE
Running the init command with changes to config file doesn’t seem to actually change the conf file

### ISSUE THREAD

**Issue by ppapapetrou76** [elastic/ecctl#45] opened 2019-11-14 13:44 UTC
Running the init command with changes to config file doesn’t seem to actually change the conf file

**Comment by marclop** [comment] 2019-11-18 07:29
I have been unable to replicate this bug, @zanbel any input you can provide here?

**Comment by zanbel** [comment] 2019-11-18 09:14
Sure. Here are the steps to try and reproduce:
1. make sure you **don't** already have an ~/.ecctl directory
2. download the relevant artifact from the [release page](https://github.com/elastic/ecctl/releases)
3. extract and run the `./ecctl init` command
4. complete the initial set up

Issue: although the initial setup appears to complete successfully the directory is not created and config file is not created or saved as expected.

**Comment by marclop** [comment] 2019-11-18 09:18
That issue was fixed in https://github.com/elastic/ecctl/pull/51, which was a bug that was easily reproducible, however the description of this PR does not match what I'm seeing. When there's a config file already created and init is called, and the properties change. the file is actually saved if the credentials are valid, which makes me think the described bug is non-existent.

**Comment by zanbel** [comment] 2019-11-18 09:23
I didn't experience the scenario you are describing so hard for me to comment. If it's not reproducible let's close the issue.

**Comment by marclop** [comment] 2019-11-18 09:35
Closing as unable to reproduce

**Closed by marclop** 2019-11-18 09:35 UTC
Labels: area:tooling, bug, invalid
