### ISSUE TITLE
ecctl create deployment --version does not work 

### ISSUE THREAD

**Issue by liza-mae** [elastic/ecctl#424] opened 2021-01-06 19:15 UTC
**./ecctl version**
```
Version:               v1.1.0
Client API Version:    2.8.0-ms48
Go version:            go1.15.2
Git commit:            a2293c25
Built:                 Thu 03 Dec 23:21:49 2020
OS/Arch:               linux / amd64
```

**./ecctl deployment create -f plan.json --name=mydeployment --version=7.10.1 --track**
```
api error: 1 error occurred:
	* clusters.cluster_invalid_plan: Version [7.5.0] is not available. Please use one of the available versions (resources.elasticsearch[0].elasticsearch.version)

```

When I was using ```ecctl_v1.0.0-beta1``` the above command worked, but now on latest released version I am getting an error, I thought the ```--version``` option would overwrite the version in the plan, but it does not seem to do that anymore.

**Comment by Kushmaro** [comment] 2021-01-26 10:57
@liza-mae this isn't a bug, but working as designed.
To our customers, version 7.5 is indeed not available anymore.
I think this specific command verifies the version with the public stackpack API.

**Comment by liza-mae** [comment] 2021-01-27 19:48
@Kushmaro this issue was not about 7.5 not being available anymore it was about that if I populate a version in the JSON plan and use the --version option to pass in another version it use to replace the version in the plan with the one passed in as arguments it does not anymore -- is that way the CLI is functioning correct ?

**Comment by liza-mae** [comment] 2021-01-27 19:52
Maybe you are saying the CLI now verifies the version in the plan before making the replacement via --version argument ?

**Comment by Kushmaro** [comment] 2021-01-31 19:18
Ah @liza-mae understood. I don't know if that's intended or not.
@marclop / @karencfv to comment further if they have more context

**Comment by karencfv** [comment] 2021-01-31 23:58
Hi @liza-mae 👋 

Deployment creation overrides are no longer supported. It's a breaking change we introduced [v1.0.0-beta3](https://www.elastic.co/guide/en/ecctl/current/ecctl-release-notes-v1.0.0-beta3.html#ecctl-release-notes-v1.0.0-beta3-breaking-changes).

With the `ecctl deployment create` command you can either use a JSON definition file or use flags, but not both.

**Comment by karencfv** [comment] 2021-02-05 02:15
Will close this issue as the question has been answered, but please feel free to open it again if you feel there's more to add :)

**Closed by karencfv** 2021-02-05 02:15 UTC
Labels: Team:Delivery, bug, wontfix
