### ISSUE TITLE
ecctl cannot create/update cluster when executed through ansible

### ISSUE THREAD

**Issue by basigabri** [elastic/ecctl#318] opened 2020-06-22 10:56 UTC
## Readiness Checklist

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I am reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior

Ecctl cli can be executed through ansible (shell/cmd) and can create/update a cluster inside Elastic service

## Current Behavior

Ecctl and the way it handles `stdin` is unable to find the json file with cluster definition when executed through ansible. Same command succeeds when executed from terminal.

## Steps to Reproduce

1. Create a task inside ansible for executing `ecctl create/update`
2. Execution of ecctl will fail with `"code\": \"root.resource_not_found`

## Context

Trying to automate deployments with ansible, faced that ecctl cannot be executed correctly.

## Your Environment

* Ecctl Version used: v1.0.0-beta3
* Environment name and version: go1.13.10
* Operating System and version: Ubuntu 18.04.4 LTS
* Ansible version: 2.9.9

##Ansible task
```
- name: Create Elastic deployment with ecctl
  shell: |
    ecctl deployment create -f {{ environment_file }} --host https://api.elastic-cloud.com --apikey {{ elastic_api_key.value }} --version {{ elastic_version }}
  args:
    executable: /bin/bash
  register: elastic_configuration 

```

## Verbose log output

```
fatal: [localhost]: FAILED! => {
    "changed": true,
    "cmd": "ecctl deployment create -f azure-westeurope.json --host https://api.elastic-cloud.com --apikey *** --version 7.7.2\n",
    "delta": "0:00:00.694734",
    "end": "2020-06-22 10:45:54.149952",
    "invocation": {
        "module_args": {
            "_raw_params": "ecctl deployment create -f azure-westeurope.json --host https://api.elastic-cloud.com --apikey *** --version 7.7.2\n",
            "_uses_shell": true,
            "argv": null,
            "chdir": null,
            "creates": null,
            "executable": "/bin/bash",
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true,
            "warn": true
        }
    },
    "msg": "non-zero return code",
    "rc": 255,
    "start": "2020-06-22 10:45:53.455218",
    "stderr": "{\n  \"errors\": [\n    {\n      \"code\": \"root.resource_not_found\",\n      \"fields\": null,\n      \"message\": \"The requested resource could not be found\"\n    }\n  ]\n}",
    "stderr_lines": [
        "{",
        "  \"errors\": [",
        "    {",
        "      \"code\": \"root.resource_not_found\",",
        "      \"fields\": null,",
        "      \"message\": \"The requested resource could not be found\"",
        "    }",
        "  ]",
        "}"
    ],
    "stdout": "",
    "stdout_lines": []
}

```

**Comment by marclop** [comment] 2020-06-24 02:12
Hi,

It seems that you're missing the `--region` flag with a value, by default `ecctl` cannot know which region the command needs to be run against. I'm fairly confident that once that's been specified the command will run as expected.

**Comment by basigabri** [comment] 2020-06-24 07:13
The problem here is that same `ecctl` command fails inside ansible, while it succeeds from terminal.  Posting here the payload and a new test with `--region` .

##1. payload

```
{
  "name": "search-dev-azure-westeurope",
  "metadata": {
    "system_owned": false
  },
  "resources": {
    "elasticsearch": [
      {
        "region": "azure-westeurope",
        "ref_id": "main-elasticsearch",
        "plan": {
          "cluster_topology": [
            {
              "node_type": {
                "data": true,
                "master": true,
                "ingest": true
              },
              "instance_configuration_id": "azure.data.highio.l32sv2",
              "zone_count": 2,
              "size": {
                "resource": "memory",
                "value": 1024
              },
              "elasticsearch": {
                "enabled_built_in_plugins": []
              }
            }
          ],
          "elasticsearch": {
            "version": "7.8.0"
          },
          "deployment_template": {
            "id": "azure-io-optimized"
          }
        },
        "settings": {
          "dedicated_masters_threshold": 6
        }
      }
    ],
    "kibana": [
      {
        "region": "azure-westeurope",
        "elasticsearch_cluster_ref_id": "main-elasticsearch",
        "ref_id": "main-kibana",
        "plan": {
          "cluster_topology": [
            {
              "instance_configuration_id": "azure.kibana.e32sv3",
              "zone_count": 1,
              "size": {
                "resource": "memory",
                "value": 1024
              }
            }
          ],
          "kibana": {
            "version": "7.8.0"
          }
        }
      }
    ],
    "apm": []
  }
}
```
## 2. Verbose logs

```
fatal: [localhost]: FAILED! => {
    "changed": true,
    "cmd": "ecctl deployment create -f /home/citrix-search-elastic-cloud-deployments/deployment/ansible/../../dev/azure-westeurope.json --host https://api.elastic-cloud.com --apikey *** --region azure-westeurope --version 7.8.0 --verbose\n",
    "delta": "0:00:08.341991",
    "end": "2020-06-24 07:00:14.796375",
    "invocation": {
        "module_args": {
            "_raw_params": "ecctl deployment create -f /home/citrix-search-elastic-cloud-deployments/deployment/ansible/../../dev/azure-westeurope.json --host https://api.elastic-cloud.com --apikey *** --region azure-westeurope --version 7.8.0 --verbose\n",
            "_uses_shell": true,
            "argv": null,
            "chdir": null,
            "creates": null,
            "executable": "/bin/bash",
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true,
            "warn": true
        }
    },
    "msg": "non-zero return code",
    "rc": 255,
    "start": "2020-06-24 07:00:06.454384",
    "stderr": "{\"errors\":[{\"code\":\"root.permission_denied\",\"message\":\"To access the resource [r:/platform/configuration/templates/deployments/default], the user must have the required authorization.\"}]}",
    "stderr_lines": [
        "{\"errors\":[{\"code\":\"root.permission_denied\",\"message\":\"To access the resource [r:/platform/configuration/templates/deployments/default], the user must have the required authorization.\"}]}"
    ],
    "stdout": "==================== Start of Request #0 ====================\nGET /api/v1/regions/azure-westeurope/platform/configuration/templates/deployments/default?format=cluster&show_instance_configurations=true HTTP/1.1\r\nHost: api.elastic-cloud.com\r\nUser-Agent: cloud-sdk-go/2.5.0-ms36\r\nAccept: application/json\r\nAuthorization: ApiKey ***\r\nAccept-Encoding: gzip\r\n\r\n\n====================  End of Request #0  ====================\n==================== Start of Response #0 ====================\nHTTP/1.1 403 Forbidden\r\nConnection: keep-alive\r\nContent-Type: application/json\r\nDate: Wed, 24 Jun 2020 07:00:13 GMT\r\nServer: fac/961895\r\nX-Cloud-Error-Codes: root.permission_denied\r\nX-Request-Id: a0e587d478c2a9ce828505e97a1ac9c7\r\n\r\n{\"errors\":[{\"code\":\"root.permission_denied\",\"message\":\"To access the resource [r:/platform/configuration/templates/deployments/default], the user must have the required authorization.\"}]}\n====================  End of Response #0  ====================",
    "stdout_lines": [
        "==================== Start of Request #0 ====================",
        "GET /api/v1/regions/azure-westeurope/platform/configuration/templates/deployments/default?format=cluster&show_instance_configurations=true HTTP/1.1",
        "Host: api.elastic-cloud.com",
        "User-Agent: cloud-sdk-go/2.5.0-ms36",
        "Accept: application/json",
        "Authorization: ApiKey ****",
        "Accept-Encoding: gzip",
        "",
        "",
        "====================  End of Request #0  ====================",
        "==================== Start of Response #0 ====================",
        "HTTP/1.1 403 Forbidden",
        "Connection: keep-alive",
        "Content-Type: application/json",
        "Date: Wed, 24 Jun 2020 07:00:13 GMT",
        "Server: fac/961895",
        "X-Cloud-Error-Codes: root.permission_denied",
        "X-Request-Id: a0e587d478c2a9ce828505e97a1ac9c7",
        "",
        "{\"errors\":[{\"code\":\"root.permission_denied\",\"message\":\"To access the resource [r:/platform/configuration/templates/deployments/default], the user must have the required authorization.\"}]}",
        "====================  End of Response #0  ===================="
    ]
}

```

**Comment by marclop** [comment] 2020-06-24 23:52
Thanks @basigabri. It looks like indeed the file isn't read and somehow the error isn't returned, I'll try to reproduce locally, investigate and come back with a patch if necessary. Thanks for providing more information.

In any case this seems to be a bug which isn't handled appropriately, I would suggest making sure that "ansible" can access the file and that the path is correct so `ecctl` can read the file when run within Ansible.

**Comment by basigabri** [comment] 2020-07-01 08:16
Thanks @marclop ! Did you manage to reproduce the issue ? The file path is correct and accessible  in my side. I tested and command succeeds when executed directly from bash. The bug occurs using ansible (shell module).

**Comment by marclop** [comment] 2020-07-02 01:49
Hi @basigabri, I haven't yet had time to take a look at it this week, I had some other commitments to take care of. I plan to look into it the coming week and have a good answer.

**Comment by marclop** [comment] 2020-07-08 02:22
Hi @basigabri, I managed to reproduce the bug locally and I pushed a fix (see the #337 PR). It'll be released with the GA version of `ecctl` so you should be able to to make ecctl work with Ansible when that is released.

**Closed** 2020-07-08 03:08 UTC
Labels: Team:Delivery, bug

**Comment by basigabri** [comment] 2020-07-08 12:23
Thanks @marclop . I build from master source, tested and work. Some more notes here:

- Creation of clusters tested and worked fine
- Updates work fine, nevertheless when `--prune-orphans` flag is used (always from within ansible), the task hangs and never terminates

thanks for your help

**Comment by marclop** [comment] 2020-07-21 03:29
@basigabri if using `--prune-orphans`, a prompt will be issued, if you want to use it within Ansible, `--force` needs to be used.
